version: "3.5"

networks:
  network:
    name: example-network
    driver: bridge

services:
  schooner:
    image: freundallein/schooner:latest
    container_name: schooner
    restart: always
    environment: 
      - PORT=8000
      - MACHINE_ID=0
      - USE_CACHE=1
      - CACHE_EXPIRE=60  # seconds
      - MAX_CACHE_SIZE=1000000  # kb
      - MAX_CACHE_ITEM_SIZE=10000  #kb
      - TARGETS=http://example:8001;http://example2:8001
      - STALE_TIMEOUT=1 # min
    networks: 
      - network
    ports:
      - 8000:8000
    depends_on: 
      - example
      - example2

  example:
    image: freundallein/schooner-example:latest
    container_name: example
    networks: 
      - network
  example2:
    image: freundallein/schooner-example:latest
    container_name: example2
    networks: 
      - network